name: Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install lld
      run: sudo apt-get update && sudo apt-get install lld -y
    - uses: actions/checkout@v3
    - name: Build
      run: make
    - uses: actions/upload-pages-artifact@v2.0.0
      with:
        path: ./
