name: Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install lld -y
  build:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make
  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/upload-pages-artifact@v2.0.0
      with:
        path: ./
  deploy:
    permissions:
      pages: write
      id-token: write
    needs: upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/deploy-pages@v2
